Update README.md
maxmind/GeoIP2-php pull request #182
Opened 2021-12-10 14:23 UTC by christophermluna

Add mention of 3rd-party tool Geoip2-update

2021-12-10 19:38 UTC, oschwald requested changes

2021-12-10 19:38 UTC, oschwald commented on README.md
> +composer. MaxMind does not offer support for this tool or maintain it.
"Composer" should be capitalized unless you are referring to the command, in which case it should be surrounded by backtickers.

2021-12-10 19:38 UTC, oschwald commented on README.md
> +[Learn more about the Geoip2-update tool for PHP and composer on its
Their GitHub project refers to the tool as "Geoip2 Update".

2021-12-10 19:38 UTC, oschwald commented on README.md
> +github page.](https://github.com/tronovav/geoip2-update)
"GitHub"

2021-12-10 19:38 UTC, oschwald commented on README.md
> +[Learn more about GeoIP Update on our developer's
Maybe "developer portal" instead as that is what the site refers to itself as? The primary reason I am commented is I wasn't sure if this should be singular or plural or possessive or not.

2021-12-15 19:59 UTC, oschwald requested changes

2021-12-15 19:59 UTC, oschwald commented on README.md
> +[Learn more about the Geoip2 Update tool for PHP and composer on its
"Composer".

2021-12-17 20:13 UTC, christophermluna commented on README.md
> +[Learn more about the Geoip2 Update tool for PHP and composer on its
sorry

2021-12-17 20:17 UTC, oschwald approved these changes

2021-12-17 20:18 UTC, merged